image: ubuntu

install:
  - sh: sudo add-apt-repository --yes ppa:rpardini/adoptopenjdk
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y adoptopenjdk-11-jdk-hotspot-installer
  - sh: sudo apt install adoptopenjdk-11-jdk-hotspot-set-default
  #/usr/lib/jvm/adoptopenjdk-11-jdk-hotspot
  - sh: export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-11-jdk-hotspot
  - sh: echo $JAVA_HOME
  - sh: export PATH=${PATH}

before_build:
  - mvn -v

build_script:
  - mvn clean package -DskipTests

test_script:
  - mvn install verify

on_finish:
  - sh: |
      find "$APPVEYOR_BUILD_FOLDER" -type f -name 'TEST*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"

artifacts:
  - path: "**/target/*.?ar"

version: "0.8.0.{build}"